[package]
name = "llm-bucket"
edition = "2021"

[dependencies]
async-trait = "0.1.88"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
tokio = { version = "1.37", features = ["macros", "rt"] }
